### ISSUE TITLE
FIPS compliance

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#24]
We need to verify that the crypto libraries we are using are FIPS 140-2 compliant, and change them if they are not.

**Comment by fosterseth** [comment]
testing setup - RHEL 8 on ec2

enable FIPS mode using `fips-mode-setup --enable` and rebooted
[more information](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening)

verify FIPS is enabled by attempting to run a non-compliant cipher, `openssl md4 README.md` returns an error related to FIPS

build receptor with `GOLANG_FIPS=1 go build cmd/receptor`

`mesh_test.go` -- keys must be generated with at least 2048 bit keys, otherwise it they cannot be verified at runtime.
https://github.com/project-receptor/receptor/pull/155

`make test` passes all tests.
