### ISSUE TITLE
Allow Listeners to set a cost per dialer

### ISSUE THREAD

**Issue by squidboylan** [ansible/receptor#31]
In the current implementation of connection costs, a listener sets a cost and a dialer must agree with it in order to connect. This restricts the flexibility of graph costs because all dialers into a single listener must have the same cost, it's not hard to imagine a network in which you would want different dialers into the same listener to have different costs (for example if they have different latencies to the same node).

There are reasons to have some negotiation of cost, for example it gives the listener some control over preventing misbehaving dialers from assigning a very cheap cost and everything getting routed through them.

A proposed solution is a listener could have a map of minimum costs for each dialer, this gives some control to the listener while allowing the dialers to set their own cost.

**Comment by ghjm** [comment]
There are two related issues here:

1. The config format is inflexible and requires a listener to have a single connection cost for all nodes that dial into it.
2. Pairs of peers are required to have the same cost statically configured in their configuration, and don't do any run-time negotiation.

Item 1 means that if you want to receive inbound connections from two peers with different path costs, you _must_ run two listeners on different ports (or different `bindaddr`s).  This could be solved by having listener cost configuration be map of costs by peer node ID, instead of just a single number.  I think this is a pretty straightforward feature improvement.  The main reason I haven't done it already is that it's awkward from a CLI perspective (`--tcp-listener cost=<what goes here?>`).

Item 2 could be used to provide better dynamic behavior of the mesh network, for example by increasing the cost of a path at run-time if high latency or packet loss is observed over it.  This would need to be done very carefully to avoid introducing things like routing loops, instability, non-convergence, etc.  This is a much larger effort that I don't foresee tackling in the short term.

**Comment by ghjm** [comment]
Some thoughts on how this should work:
* Both sides of the connection still have to agree on a cost - I don't think there should be any changes to the network protocol.
* Dialers still only get one cost.  This is also unchanged.
* Listeners need to be able to specify a cost per peer (dialer), as a map of node ID to cost.  I think it's okay if this uses the YAML map syntax in the config file.  If you want to specify a map of node IDs to costs on the command line, you'll have to write JSON - but anyone configuring their listener at this level of complexity should be using a config file anyway.
* On connection, a listener will have to decide what it thinks the connection cost should be, and it can only do this after it discovers the node ID of the dialer.  This might get a bit hairy since the protocol start is a single function called by both dialers and listeners, so this change may need to introduce some asymmetry.
* You should still be able to set a default cost for a listener that will be applied to any (allowed) node ID not in the map.  I imagine this can be done by leaving the current listener cost field, and using it when the node ID doesn't have a match in the map.

**Comment by squidboylan** [comment]
Added automated testing for this in https://github.com/project-receptor/receptor/pull/106
