### ISSUE TITLE
Increase minimum TLS version

### ISSUE THREAD

**Issue by eqrx** [ansible/receptor#373]
Hey all!

Currently, we leave the field setting the minimum TLS version to use in server and client connections blank, which lets it default to TLS 1.0. This means that all of TLS 1.0, 1.1, 1.2 and 1.3 are allowed. I would like to increase the minimum TLS version to 1.3 to prevent several attack possibilities.

Problems: Go supports 1.3 since the beginning of 2019 so I find it safe to assume that there are no installations that don't support it. I am not aware if we interface with very old non go clients. Do we? 

Upgrading: The protocol version is always negotiated between server & client. It would only result in a (much) smaller common protocol set if only one of them has a higher minimal version. Therefore, upgrades can be done in any order.

Thanks for reading!

**Comment by ghjm** [comment]
When built with the Red Hat Go toolchain, the Go standard TLS libraries are transparently replaced with calls to openssl, so that Go programs can be FIPS compliant.  The version of openssl on RHEL7 does not support TLS 1.3.  So if you want Receptor to be able to run in FIPS mode on RHEL7, the max TLS version you can support is 1.2.  I agree everything below 1.2 can be jettisoned (and honestly thought I'd already done that).

**Comment by shanemcd** [comment]
I _think_ only supporting FIPS on RHEL 8+ is fine. @wenottingham thoughts?

**Comment by wenottingham** [comment]
RHEL7 is not a concern for me personally. I'm fine with removing anything below TLS 1.2.

**Comment by eqrx** [comment]
Sorry for the delay, was on PTO. I have opened PR #382 (can't link it though because of missing permissions). I also dared to reduce the cipher set because TLS 1.2 has a pretty broad range of them. Is that okay? 

Also, than @ghjm for explaining :)

**Comment by shanemcd** [comment]
Closing this, I merged #382.
