### ISSUE TITLE
Do we need the build tags?

### ISSUE THREAD

**Issue by eqrx** [ansible/receptor#408]
Just curious, are we actually using the build tags for something? If one disables all the features of receptor the binary size drops from 35MB to 8.6MB (non stripped) but do we actually need such fine configuration?

Do we have a use case where we need to restrict the feature set?

@ghjm could you please enlighten me?

Thank you for your time and have a nice day :)

**Comment by ghjm** [comment]
The build tags exist because Jag wanted to be able to produce a 'hardened' Receptor build where it was guaranteed that, even if misconfigured, the proxy features couldn't possibly be used for exfiltration or other bad purposes when deployed in a secure network.  Shrinking the binary size was never much of a concern.

If we do care about the binary size, by my count about 30M is the Kubernetes libraries pulled in by Workceptor.  The other build tags don't have much effect on the final size.

The current Receptor architecture means that if you want an application running on a given Netceptor instance, it has to be compiled in to a single go binary.  It's been in the back of my mind for a long time to make an attempt at implementing loadable Receptor apps, that would look something like this:

```
---
- node:
    id: foo

- plugin:
    path: "/path/to/plugin.so"
    config:
      key: value
      otherkey: othervalue
```

This would use https://pkg.go.dev/plugin to load plugin.so, and would have some kind of calling convention where Receptor calls a `start()` method and passes in some kind of interface including (at least) a pointer to a Netceptor, and a way to add control service functions.  Eventually, the main Receptor binary could be just Netceptor and controlsvc, with everything else (Workceptor, the proxies, the IP router, etc) implemented as plugins.  This would allow Receptor apps to be developed on their own release schedules, separately from the main Receptor releases, if that turns out to make sense.
